apiVersion: apps/v1
kind: Deployement
metadata:
  name: microservicesnode
  labels:
    app: nodeapp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nodeapp
    template:
      metadata:
