services:
  # Auth DB
  mongo-auth:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${AUTHDB_ADMIN_UNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${AUTHDB_ADMIN_PASS}"
    volumes:
      - auth_db:/data/db
    networks:
      - internal

  # Auth service
  auth-service:
    build:
      # It defines path to the directory
      context: ./src/auth
      # It defines path to the dockerfile
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    command: npm run dev
    volumes:
      - ./src/auth:/app
      - node_modules_auth:/app/node_modules
    networks:
      - internal
    depends_on:
      - mongo-auth

  #Gateway
  gateway:
    build:
      # It defines path to the directory
      context: ./src/gateway
      # It defines path to the dockerfile
      dockerfile: Dockerfile
    env_file:
      # Path to env file
      - ./.env
    ports:
      # Variables declared inside .env file
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    command: npm run dev
    volumes:
      # This is the bind mount which will reflect file changes in container
      - ./src/gateway:/app
      # This is the node_modules volume
      - node_modules_gateway:/app/node_modules
    networks:
      - internal
    depends_on:
      - auth-service

networks:
  internal:
    driver: bridge
volumes:
  auth_db:
  node_modules_auth:
  node_modules_gateway:
